Cyberabad/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'Cyberabad'
urlpatterns = [
    path('upload/',views.upload_Video,name='upload'),
    path('all/',views.all_Videos,name='allVideos'),
    path('<int:id>/',views.display_Video,name='singleVideo'),
    path('<int:id>/postcomment/',views.post_Comment,name="postComment"),
    path('<int:id>/editcomment/',views.edit_comment,name="editComment"),
    path('<int:id>/removecomment/',views.remove_comment,name="removeComment"),
    path('rithish/',views.rithish,name='newVideo'),
    path('sendMedia/',views.sendMedia,name='sendMedia'),
    path('location/',views.getGPS,name='location'),
]

accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'
urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('uploaded/',views.uploadedVideos,name='uploaded'),
    path('video/',views.removeMedia,name='removeMedia'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.views.generic.base import TemplateView
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls',namespace="accounts")),
    path('accounts/', include('django.contrib.auth.urls')),
    path('',views.HomePage.as_view(), name="home"),
    path('',include('Cyberabad.urls',namespace="Cyberabad")),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!-- templates/base.html -->
{% load staticfiles %}

<html>
<head>
<head>
    <meta charset="utf-8">
    <title>Video App</title>
    <script src="https://code.jquery.com/jquery-1.11.3.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"> -->
    <link rel="stylesheet" href="{% static 'css/master.css'%}">
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
  </head>
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="{% url 'home' %}">Video Portal</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  {% if user.is_authenticated %}
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        
        <ul class="navbar-nav ml-md-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            {% if user.is_staff %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'Cyberabad:upload' %}">upload</a>
                </li>
            {% endif %}
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Profile
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="#">{{user}}</a>
                {% if user.is_staff %}
                    <a class="dropdown-item" href="{% url 'accounts:uploaded' %}">uploaded videos</a>
                {% endif %}
                <a class="dropdown-item" href="{% url 'password_change' %}">Change password</a>
                <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
                </div>
            </li>
        </ul>
    </div>
   {% else %}
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-md-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'login' %}">Login <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:signup' %}">Register</a>
                </li>
            </ul>
        </div>
   {% endif %} 
</nav>
  <div class="container-fluid">
    {% block content %}
    {% endblock %}
  </div>
  <footer class="footer" style="bottom:0">
    <div class="container" style="border-top: 1pt solid rgba(0, 0, 0, 0.1); text-align: center;">
      <span class="text-muted">
        &copy; Center for Visual Information Technology (CVIT), IIIT Hyderabad.
      </span>
    </div>
  </footer>
</body>
</html>

templates/home.html
<!-- templates/home.html-->
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
{% endblock %}